theme: jekyll-theme-cayman
title: Equation of The Day
github:
  is_project_page: false
  is_user_page: false
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true